# Generated by Django 3.1.1 on 2020-09-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='nav_copy_right',
            field=models.CharField(default='amirhossein', max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='social2_link',
            field=models.URLField(default='your url here'),
        ),
        migrations.AddField(
            model_name='setting',
            name='social_link',
            field=models.URLField(default='your url here'),
        ),
    ]
